context("Regression tests for data output")

wader_data_path <- tempdir()

test_that("data generated by max counts is same", {
  skip_on_cran()
  data <- max_counts(path = wader_data_path) %>%
    dplyr::filter(year < 2021)
  expect_equal(sum(data$count),697589)
})

test_that("data generated by ground counts is same", {
  skip_on_cran()
  data <- ground_counts(path = wader_data_path) %>%
    dplyr::filter(year < 2021)
  expect_equal(sum(data$total),33459)
  data <- ground_counts(path = wader_data_path,level="point") %>%
    dplyr::filter(year < 2021)
  expect_equal(sum(data$count,na.rm=TRUE),29245)
})

test_that("data generated by weather default is same", {
  skip_on_cran()
  data <- weather(path = wader_data_path) %>%
    dplyr::filter(year < 2021)
  expect_equal(sum(data$mintemp,na.rm=TRUE),516752.4)
  expect_equal(sum(data$meantemp,na.rm=TRUE),709781.1)
  expect_equal(sum(data$precipitation,na.rm=TRUE),119563.2)
  expect_equal(sum(data$cool_precip,na.rm=TRUE),1482.099)
})

test_that("data generated by monthly weather is same", {
  skip_on_cran()
  data <- weather(path = wader_data_path, level = "monthly") %>%
    dplyr::filter(year < 2021)
  expect_equal(sum(data$mintemp,na.rm=TRUE),17061.43)
  expect_equal(sum(data$meantemp,na.rm=TRUE),23442.19)
  expect_equal(sum(data$precipitation,na.rm=TRUE),119563.2)
  expect_equal(round(sum(data$cool_precip,na.rm=TRUE),4),49.0255)
})
