context("Regression tests for data output")

wader_data_path <- tempdir()

test_that("data generated by max counts is same", {
  skip_on_cran()
  data <- max_counts(path = wader_data_path) %>%
    dplyr::filter(year < 2021)
  attributes(data) <- attributes(data)[sort(names(attributes(data)))]
  expect_known_hash(data, "9dd033e385")
})

test_that("data generated by weather default is same", {
  skip_on_cran()
  data <- weather(path = wader_data_path) %>%
    dplyr::filter(year < 2021)
  attributes(data) <- attributes(data)[sort(names(attributes(data)))]
  expect_known_hash(data, "7e1f355cbc")
})

test_that("data generated by monthly weather is same", {
  skip_on_cran()
  data <- weather(path = wader_data_path, level = "monthly") %>%
    dplyr::filter(year < 2021)
  attributes(data) <- attributes(data)[sort(names(attributes(data)))]
  expect_known_hash(data, "b8b64b2eb9")
})
